NAME: 'bagoftricks-third-stage'
OUTPUT_DIR: './output/imagenet-lt/'
SHOW_STEP: 200
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'iNaturalist'
  TRAIN_JSON: '/mnt/data3/zhangys/programs/BagofTricks-LT/ImageNet_LT_train.json'
  VALID_JSON: '/mnt/data3/zhangys/programs/BagofTricks-LT/ImageNet_LT_val.json'

NETWORK:
  PRETRAINED:  True
  PRETRAINED_MODEL: './output/imagenet-lt/bagoftricks-second-stage/models/epoch_40.pth'


BACKBONE:
  TYPE: 'res10'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 512
  MAX_EPOCH: 20
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.002
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [8, 16]
    LR_FACTOR: 0.1
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'balance'

  DISTRIBUTED: False
  SYNCBN: True
  APEX: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip", "color_jitter")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 512
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'