NAME: 'bagoftricks-third-stage'
OUTPUT_DIR: './output/cifar10_im50/'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'

DATASET:
  DATASET: 'CIFAR'
  TRAIN_JSON: '/mnt/ramdisk/CIFAR-LT/cifar10_imbalance50_train.json'
  VALID_JSON: '/mnt/ramdisk/CIFAR-LT/cifar10_imbalance50_valid.json'

NETWORK:
  PRETRAINED:  True
  PRETRAINED_MODEL: './output/cifar10_im50/bagoftricks-second-stage/models/epoch_80.pth'


BACKBONE:
  TYPE: 'res32_cifar'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 20
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [8, 16]
    LR_FACTOR: 0.1
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'balance'

  DISTRIBUTED: False
  SYNCBN: True
  APEX: False

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'